### ISSUE TITLE
Cleaned up docs

### ISSUE THREAD

**Issue by cjmurphy93** [cjmurphy93/BluTube#2]
I cleaned up the Design Docs following your recommendations.

**Comment by vawhitehouse** [comment]
Updates are looking great! A few more notes:

## Backend Routes
- [ ] Sorry, my last comment on nested routes was vague. I meant to talk more about this when we met. We generally only want/need one wildcard in each backend route. Checkout this [reading on nested routing](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md) . Basically, we probably only need to nest the `index` of `comments` under `videos`. Other resources for `comments` can remain at the top level of the api namespace
- [ ] Also, think about what routing/components you will need your `Searching Videos` MVP
